name: Deploy With Kamal

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key for DigitalOcean
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 159.65.88.129 >> ~/.ssh/known_hosts 

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  

    - name: Install Kamal gem
      run: gem install kamal

    - name: Setup Kamal
      env:
        KAMAL_REGISTRY_PASSWORD: $KAMAL_REGISTRY_PASSWORD
        DATABASE_URL: $DATABASE_URL
        SECRET_KEY_BASE: $SECRET_KEY_BASE
        POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        POSTGRES_DB: $POSTGRES_DB
        TOKEN: $TOKEN
        PHX_HOST: $PHX_HOST
      run: kamal setup

    - name: Deploy with Kamal
      env:
        KAMAL_REGISTRY_PASSWORD: ${{secrets.KAMAL_REGISTRY_PASSWORD}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        SECRET_KEY_BASE: ${{secrets.SECRET_KEY_BASE}}
        POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        TOKEN: ${{secrets.TOKEN}}
        PHX_HOST: ${{secrets.PHX_HOST}}
      run: kamal deploy
